export 'package:almagestv2/screens/check_auth_screen.dart';
export 'package:almagestv2/screens/home_screen.dart';
export 'package:almagestv2/screens/admin_screen.dart';
export 'package:almagestv2/screens/login_screen.dart';
export 'package:almagestv2/screens/register_screen.dart';
export 'package:almagestv2/screens/loading_screen.dart';
export 'package:almagestv2/screens/update_screen.dart';
export 'package:almagestv2/screens/opinion_screen.dart';
export 'package:almagestv2/screens/form_opinion_screen.dart';
